### variables declaration

In [12]:
a =4

In [19]:
a='4'

In [18]:
a=67.78

In [20]:
type(a)

str

### String

In [23]:
str1 = '5'

In [28]:
str1+='5   '

In [30]:
str1=''

In [33]:
type(str1)

str

### List

In [38]:
list1= [1,2,3,4,534,65,2,4,'ab',45.564]

In [39]:
list1.append(67)

In [41]:
##use tab after '.' to get all functionalities
list1.insert(3,'ab')

In [43]:
list1

[1, 2, 3, 'ab', 4, 534, 65, 2, 4, 'ab', 45.564, 67]

In [45]:
list2 = [[1,2,3],[2,3,4],[4,5,6]]

In [46]:
list2

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]

In [47]:
list2.append([1,8])

In [48]:
list2

[[1, 2, 3], [2, 3, 4], [4, 5, 6], [1, 8]]

In [49]:
###for accessing

In [53]:
list2[2][2]

6

In [91]:
## ordered 
## can contain duplicates

### tuple

In [54]:
tuple1 = (1,2)

In [55]:
tuple2=(1,3,4,6,6)

In [60]:
tuple2[3]

6

In [62]:
list3 = [(1,2),(45,78),('ab','56')]

In [63]:
list3

[(1, 2), (45, 78), ('ab', '56')]

In [64]:
##lists are faster

In [73]:
tuple2.index(4)

2

### dictionary

In [74]:
dict1 = {}

In [75]:
dict1[4]=5

In [76]:
dict1[6]=1

In [78]:
dict1['ab'] = 67.89

In [79]:
dict1

{4: 5, 6: 1, 'ab': 67.89}

In [80]:
dict1[9] = [1,3,5,67]

In [81]:
dict1

{9: [1, 3, 5, 67], 4: 5, 6: 1, 'ab': 67.89}

In [82]:
'aniket' in dict1

False

In [85]:
ab in dict1

NameError: name 'ab' is not defined

In [86]:
'ab' in dict1

True

In [88]:
list1

[1, 2, 3, 'ab', 4, 534, 65, 2, 4, 'ab', 45.564, 67]

In [89]:
'ab' in list1

True

In [106]:
type(dict1[9])

list

### set

In [90]:
##it hold only distict values
##unordered

In [92]:
list1

[1, 2, 3, 'ab', 4, 534, 65, 2, 4, 'ab', 45.564, 67]

In [93]:
set(list1)

{1, 2, 3, 4, 65, 67, 45.564, 534, 'ab'}

In [95]:
type(set(list1))

set

In [97]:
list1 + list2

[1,
 2,
 3,
 'ab',
 4,
 534,
 65,
 2,
 4,
 'ab',
 45.564,
 67,
 [1, 2, 3],
 [2, 3, 4],
 [4, 5, 6],
 [1, 8]]

In [101]:
list4 = [[1,2,3],[1,23,3,45,5],['ag','df','434'],8,'ab',list1]

In [102]:
list4

[[1, 2, 3],
 [1, 23, 3, 45, 5],
 ['ag', 'df', '434'],
 8,
 'ab',
 [1, 2, 3, 'ab', 4, 534, 65, 2, 4, 'ab', 45.564, 67]]

## coding format

In [120]:
for i in range(10):
    print(i)
    print(i+i)
    if i == 3:
        print(i,'found')
        break
    elif i ==6:
        print(i,'found')
        break

0
0
1
2
2
4
3
6
3 found


# list comprehension

In [123]:
[i for i in range(10) if i>3]

[4, 5, 6, 7, 8, 9]

In [136]:
list5 = [1,2,3,4,'ab']
list6 = [6,7,8,9,56]

In [140]:
[[(type(i),type(y))] for i,y in zip(list5,list6)]

[[(int, int)], [(int, int)], [(int, int)], [(int, int)], [(str, int)]]

In [141]:
[[(i,y)] for i,y in zip(list5,list6)]

[[(1, 6)], [(2, 7)], [(3, 8)], [(4, 9)], [('ab', 56)]]

In [4]:
list1=[['a',4],['b',8.8],['c','d']]

In [5]:
list1

[['a', 4], ['b', 8.8], ['c', 'd']]

In [9]:
type(list1[-1:])

list

In [13]:
list1[-2][1]

8.8

# List Manipulation 

In [7]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
# Restricting the change in previous list
areas_copy = list(areas)
#list(areas) or areas[:]

# Change areas_copy
areas_copy[0] = 5.0
# Print areas
print(areas)
#Previous list will get change 
areas_copy=areas
areas_copy[0]  = 5.0
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


# Sorted example


In [2]:
a=['apple','ass','astrology','ancient','age']

In [5]:
print(sorted(a))
print(sorted(a,key=len))
print(sorted(a,key=len,reverse=True))

['age', 'ancient', 'apple', 'ass', 'astrology']
['ass', 'age', 'apple', 'ancient', 'astrology']
['astrology', 'ancient', 'apple', 'ass', 'age']


# Built in Method

In [12]:
str='poolhouse'
print(str)
print(str.upper())
print(str.capitalize())
print(str.count('o'))
print(str.index('h'))
a=[1,2,4,2,3,6,2,1,5,6]
print(type(a))
print(a.index(2))
print(a.count(2))

poolhouse
POOLHOUSE
Poolhouse
3
4
<class 'list'>
1
3


# Numpy

In [82]:
import numpy as np
l=np.array([[1,2,9],[3,4,7],[5,6,8]])
m=np.array([2,3,1]);
print(l*m)
print(l[:,0:2])
print(l)
print(np.corrcoef(l[:,0],l[:,1]))
p=[1,2,3,4]
print(sorted(p,reverse=True))

x = np.array([14, 21, 24, 24])
y = np.array([12, 6, 23, 29])
z = np.array([x, y])
print(z.shape)
print(z.size)
p = [[3, "A", 5], [2, 6, "B"], ["C", "D", "E"]]
print(p[1][0:2])
x = np.array([19, 2, 13, 4])
print(x[0:3])
p=[1,2,3,4]
print(p.remove(1))
print(p)

[[ 2  6  9]
 [ 6 12  7]
 [10 18  8]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 9]
 [3 4 7]
 [5 6 8]]
[[ 1.  1.]
 [ 1.  1.]]
[4, 3, 2, 1]
(2, 4)
8
[2, 6]
[19  2 13]
None
[2, 3, 4]


In [84]:
store = np.array([0, 9, 0, 1])
cost  = np.array([82, 82, 73, 73])
np_cols = np.array((store, cost))
print(np_cols)

[[ 0  9  0  1]
 [82 82 73 73]]


In [119]:
p=[1,2,2,4,5,6]
print(x[x>4])
print(p.count(2))
print("Range is ",range(len(p)))
for i in range(len(p)):
    print(i,p[i])
for index,value in enumerate(p): 
    print(value)
name="Mohua"
print(name.replace("o","oo"))

[19 13]
2
Range is  range(0, 6)
0 1
1 2
2 2
3 4
4 5
5 6
1
2
2
4
5
6
Moohua


In [116]:
import numpy as np
store = np.array([0, 9, 0, 1,8])
cost  = np.array([82, 82, 73, 73,8])
np_cols = np.column_stack((store, cost))
print(np_cols)

[[ 0 82]
 [ 9 82]
 [ 0 73]
 [ 1 73]
 [ 8  8]]


In [118]:
p = ['j', 'x', 'n', 'k', 'e', 'x']
del(p[2:4])
print(p)


['j', 'x', 'e', 'x']


In [131]:
import numpy as np
x=[1,2,3,4]
y=[5]
print(np.array(x)*np.array(y))

[ 5 10 15 20]


In [161]:
import numpy as np
x=np.array([[277,3,1],[3,5,1]],dtype=np.int16)#change datatype in second arg
print(x.dtype)
print(x.shape)
print(x.data)
print(x.strides)
print(x.astype(float))

int16
(2, 3)
(6, 2)
[[ 277.    3.    1.]
 [   3.    5.    1.]]


In [150]:
import numpy
print(numpy.__version__)

1.11.1


In [164]:
# Create an array of ones
x=np.ones((3,2))
print('Printing X')
print(x)

# Create an array of zeros
y=np.zeros((3,2,4),dtype=np.int16)
print('Printing Y')
print(y)

# Create an array with random values
x1=np.random.random((2,2))
print('Printing X1')
print(x1)
# Create an empty array
y1=np.empty((3,2))
print('Printing Y1')
print(y1)

# Create a full array
z=np.full((2,2),8,dtype=int)
print('Printing Z')
print(z)
# Create an array of evenly-spaced values
z1=np.arange(10,25,2)
print('Printing z1')
print(z1)

# Create an array of evenly-spaced values
a=np.linspace(0,2,5)
print('Printing a')
print(a)


Printing X
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
Printing Y
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
Printing X1
[[ 0.55569218  0.01210121]
 [ 0.32284084  0.49044993]]
Printing Y1
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
Printing Z
[[8 8]
 [8 8]]
Printing z1
[10 12 14 16 18 20 22 24]
Printing a
[ 0.   0.5  1.   1.5  2. ]


In [168]:
import os
print(os.path.basename(os.getcwd()))
print(os.getcwd())

mohua_das_gupta
C:\Users\mohua_das_gupta


In [170]:
import numpy as np
x, y, z = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=True)

ValueError: could not convert string to float: b'Value1'

In [7]:
print(bool(1),bool(0),int(True),int(False),25%4,25/4)

True False 1 0 1 6.25


In [25]:
x="Manish Kanti Das Gupta"
print(x[::2])
print(x[0:6:2])
print(len(x))
print(x+" is my father")
print(3*x)
#x[0]='m'---Error
print(x[0])
y=x.replace('Das Gupta','Dasgupta')
print(x+'\n'+y)
print(x.find('Dasd'))
print(x.find('Das'))

Mns at a ut
Mns
22
Manish Kanti Das Gupta is my father
Manish Kanti Das GuptaManish Kanti Das GuptaManish Kanti Das Gupta
M
Manish Kanti Das Gupta
Manish Kanti Dasgupta
-1


In [27]:
import sys 
print(sys.version)

3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
